from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from typing import Iterable, Mapping

from .experience import TradeSide
from .markets import InstrumentEconomics


class BacktestMode(StrEnum):
    CHEAP_SCREEN = "cheap_screen"
    REALISTIC_LEDGER = "realistic_ledger"


@dataclass(frozen=True, slots=True)
class PriceMark:
    at: datetime
    symbol: str
    price: float

    def __post_init__(self) -> None:
        if self.at.tzinfo is None or self.at.utcoffset() is None:
            raise ValueError("price marks must be timezone-aware")
        if not self.symbol.strip() or self.price <= 0:
            raise ValueError("price mark requires symbol and positive price")


@dataclass(frozen=True, slots=True)
class SimulatedTrade:
    trade_id: str
    symbol: str
    side: TradeSide
    entry_at: datetime
    exit_at: datetime
    entry_price: float
    exit_price: float
    volume: float
    entry_cost: float = 0.0
    exit_cost: float = 0.0
    swap_cost: float = 0.0

    def __post_init__(self) -> None:
        if not self.trade_id.strip() or not self.symbol.strip():
            raise ValueError("trade id and symbol are required")
        if self.entry_at.tzinfo is None or self.entry_at.utcoffset() is None:
            raise ValueError("entry timestamp must be timezone-aware")
        if self.exit_at.tzinfo is None or self.exit_at.utcoffset() is None:
            raise ValueError("exit timestamp must be timezone-aware")
        if self.exit_at <= self.entry_at:
            raise ValueError("exit must occur after entry")
        if self.entry_price <= 0 or self.exit_price <= 0 or self.volume <= 0:
            raise ValueError("trade prices and volume must be positive")
        if min(self.entry_cost, self.exit_cost, self.swap_cost) < 0:
            raise ValueError("transaction costs cannot be negative")


@dataclass(frozen=True, slots=True)
class LedgerPoint:
    at: datetime
    balance: float
    equity: float
    realized_pnl: float
    unrealized_pnl: float
    margin_used: float
    drawdown_fraction: float
    open_positions: int


@dataclass(frozen=True, slots=True)
class BacktestResultV2:
    mode: BacktestMode
    starting_equity: float
    ending_balance: float
    ending_equity: float
    net_pnl: float
    max_drawdown_fraction: float
    trade_count: int
    ledger: tuple[LedgerPoint, ...]


@dataclass(frozen=True, slots=True)
class FoldRange:
    fold_id: str
    train_start: int
    train_end: int
    test_start: int
    test_end: int

    def __post_init__(self) -> None:
        if not (0 <= self.train_start < self.train_end <= self.test_start < self.test_end):
            raise ValueError("fold ranges must be chronological and non-overlapping")


def _price_pnl(
    *,
    entry: float,
    mark: float,
    volume: float,
    side: TradeSide,
    economics: InstrumentEconomics,
) -> float:
    direction = 1.0 if side is TradeSide.LONG else -1.0
    ticks = (mark - entry) / economics.tick_size
    return direction * ticks * economics.tick_value * volume


def trade_gross_pnl(trade: SimulatedTrade, economics: InstrumentEconomics) -> float:
    return _price_pnl(
        entry=trade.entry_price,
        mark=trade.exit_price,
        volume=trade.volume,
        side=trade.side,
        economics=economics,
    )


def trade_net_pnl(trade: SimulatedTrade, economics: InstrumentEconomics) -> float:
    return trade_gross_pnl(trade, economics) - trade.entry_cost - trade.exit_cost - trade.swap_cost


def simulate_portfolio(
    trades: Iterable[SimulatedTrade],
    marks: Iterable[PriceMark],
    economics_by_symbol: Mapping[str, InstrumentEconomics],
    *,
    starting_equity: float,
) -> BacktestResultV2:
    """Chronological account ledger with overlapping positions and mark-to-market equity.

    Trades are already generated by a frozen strategy. This function deliberately owns only
    account economics: realized/unrealized PnL, costs, margin, equity, and drawdown.
    """
    if starting_equity <= 0:
        raise ValueError("starting equity must be positive")
    trade_rows = tuple(trades)
    mark_rows = tuple(marks)
    if len({trade.trade_id for trade in trade_rows}) != len(trade_rows):
        raise ValueError("trade ids must be unique")
    missing = sorted({trade.symbol for trade in trade_rows} - set(economics_by_symbol))
    if missing:
        raise ValueError(f"missing instrument economics: {','.join(missing)}")

    event_times = sorted(
        {trade.entry_at for trade in trade_rows}
        | {trade.exit_at for trade in trade_rows}
        | {mark.at for mark in mark_rows}
    )
    marks_at: dict[datetime, list[PriceMark]] = {}
    entries_at: dict[datetime, list[SimulatedTrade]] = {}
    exits_at: dict[datetime, list[SimulatedTrade]] = {}
    for mark in mark_rows:
        marks_at.setdefault(mark.at, []).append(mark)
    for trade in trade_rows:
        entries_at.setdefault(trade.entry_at, []).append(trade)
        exits_at.setdefault(trade.exit_at, []).append(trade)

    balance = float(starting_equity)
    realized_total = 0.0
    high_water = float(starting_equity)
    last_price: dict[str, float] = {}
    open_trades: dict[str, SimulatedTrade] = {}
    ledger: list[LedgerPoint] = []
    max_drawdown = 0.0

    for at in event_times:
        for mark in sorted(marks_at.get(at, ()), key=lambda item: item.symbol):
            last_price[mark.symbol] = mark.price

        # Close before opening at the same instant: released risk/capital is available first.
        for trade in sorted(exits_at.get(at, ()), key=lambda item: item.trade_id):
            if trade.trade_id not in open_trades:
                raise ValueError(f"closing unknown trade: {trade.trade_id}")
            economics = economics_by_symbol[trade.symbol]
            pnl = trade_net_pnl(trade, economics)
            balance += pnl
            realized_total += pnl
            last_price[trade.symbol] = trade.exit_price
            del open_trades[trade.trade_id]

        for trade in sorted(entries_at.get(at, ()), key=lambda item: item.trade_id):
            if trade.trade_id in open_trades:
                raise ValueError(f"duplicate open trade: {trade.trade_id}")
            balance -= trade.entry_cost
            realized_total -= trade.entry_cost
            # trade_net_pnl includes entry cost, so avoid charging it again on close.
            open_trades[trade.trade_id] = SimulatedTrade(
                trade.trade_id,
                trade.symbol,
                trade.side,
                trade.entry_at,
                trade.exit_at,
                trade.entry_price,
                trade.exit_price,
                trade.volume,
                entry_cost=0.0,
                exit_cost=trade.exit_cost,
                swap_cost=trade.swap_cost,
            )
            last_price[trade.symbol] = trade.entry_price

        unrealized = 0.0
        margin = 0.0
        for trade in open_trades.values():
            economics = economics_by_symbol[trade.symbol]
            mark = last_price.get(trade.symbol, trade.entry_price)
            unrealized += _price_pnl(
                entry=trade.entry_price,
                mark=mark,
                volume=trade.volume,
                side=trade.side,
                economics=economics,
            )
            margin += trade.entry_price * economics.contract_size * trade.volume * economics.margin_rate

        equity = balance + unrealized
        high_water = max(high_water, equity)
        drawdown = (high_water - equity) / high_water if high_water > 0 else 0.0
        max_drawdown = max(max_drawdown, drawdown)
        ledger.append(
            LedgerPoint(
                at=at,
                balance=balance,
                equity=equity,
                realized_pnl=realized_total,
                unrealized_pnl=unrealized,
                margin_used=margin,
                drawdown_fraction=drawdown,
                open_positions=len(open_trades),
            )
        )

    if open_trades:
        raise ValueError("backtest ended with open trades")
    ending_equity = ledger[-1].equity if ledger else starting_equity
    return BacktestResultV2(
        mode=BacktestMode.REALISTIC_LEDGER,
        starting_equity=starting_equity,
        ending_balance=balance,
        ending_equity=ending_equity,
        net_pnl=ending_equity - starting_equity,
        max_drawdown_fraction=max_drawdown,
        trade_count=len(trade_rows),
        ledger=tuple(ledger),
    )


def purged_walk_forward_ranges(
    total_rows: int,
    *,
    train_rows: int,
    test_rows: int,
    purge_rows: int = 0,
    embargo_rows: int = 0,
    max_folds: int = 64,
) -> tuple[FoldRange, ...]:
    """Build bounded chronological folds with explicit train/test separation.

    `purge_rows` removes observations immediately before each test block. `embargo_rows`
    advances the next test block after the previous test, preventing immediate reuse of its
    boundary neighborhood.
    """
    if min(total_rows, train_rows, test_rows, max_folds) < 1:
        raise ValueError("row counts and max_folds must be positive")
    if purge_rows < 0 or embargo_rows < 0:
        raise ValueError("purge and embargo cannot be negative")
    folds: list[FoldRange] = []
    test_start = train_rows + purge_rows
    while test_start + test_rows <= total_rows and len(folds) < max_folds:
        train_end = test_start - purge_rows
        train_start = max(0, train_end - train_rows)
        folds.append(
            FoldRange(
                fold_id=f"wf-{len(folds):03d}",
                train_start=train_start,
                train_end=train_end,
                test_start=test_start,
                test_end=test_start + test_rows,
            )
        )
        test_start += test_rows + embargo_rows
    return tuple(folds)


def evaluation_slice[T](rows: tuple[T, ...], *, warmup_rows: int) -> tuple[T, ...]:
    """Warm-up primes indicators but is never scored as evaluation performance."""
    if warmup_rows < 0 or warmup_rows > len(rows):
        raise ValueError("invalid warmup row count")
    return rows[warmup_rows:]
